INSERT INTO players (id, name, position) VALUES
    (1, 'Lionel Messi', 'Forward'),
    (2, 'Cristiano Ronaldo', 'Forward'),
    (3, 'Kevin De Bruyne', 'Midfielder'),
    (4, 'Virgil van Dijk', 'Defender'),
    (5, 'Sergio Ramos', 'Defender'),
    (6, 'Neymar Jr.', 'Forward'),
    (7, 'Kylian Mbappé', 'Forward'),
    (8, 'Mohamed Salah', 'Forward'),
    (9, 'Robert Lewandowski', 'Forward'),
    (10, 'Eden Hazard', 'Forward'),
    (11, 'Luka Modrić', 'Midfielder'),
    (12, 'Thibaut Courtois', 'Goalkeeper'),
    (13, 'Karim Benzema', 'Forward'),
    (14, 'Toni Kroos', 'Midfielder'),
    (15, 'Fede Valverde', 'Midfielder'),
    (16, 'Ferland Mendy', 'Defender'),
    (17, 'Vinícius Júnior', 'Forward'),
    (18, 'David Alaba', 'Defender'),
    (19, 'Casemiro', 'Midfielder'),
    (20, 'Isco', 'Midfielder'),
    (21, 'Marcelo', 'Defender'),
    (22, 'Eden Hazard', 'Forward'),
    (23, 'Raheem Sterling', 'Forward'),
    (24, 'Phil Foden', 'Midfielder'),
    (25, 'Jack Grealish', 'Forward'),
    (26, 'Riyad Mahrez', 'Forward'),
    (27, 'Bernardo Silva', 'Midfielder'),
    (28, 'Ilkay Gündogan', 'Midfielder'),
    (29, 'Rodri', 'Midfielder'),
    (30, 'Aymeric Laporte', 'Defender'),
    (31, 'John Stones', 'Defender'),
    (32, 'Kyle Walker', 'Defender'),
    (33, 'Ederson', 'Goalkeeper'),
    (34, 'Alisson Becker', 'Goalkeeper'),
    (35, 'Trent Alexander-Arnold', 'Defender'),
    (36, 'Andrew Robertson', 'Defender'),
    (37, 'Mohamed Salah', 'Forward'),
    (38, 'Sadio Mané', 'Forward'),
    (39, 'Thiago Alcântara', 'Midfielder'),
    (40, 'Fabinho', 'Midfielder'),
    (41, 'Jordan Henderson', 'Midfielder'),
    (42, 'Diogo Jota', 'Forward'),
    (43, 'Roberto Firmino', 'Forward'),
    (44, 'Virgil van Dijk', 'Defender'),
    (45, 'Gianluigi Donnarumma', 'Goalkeeper'),
    (46, 'Marquinhos', 'Defender'),
    (47, 'Sergio Ramos', 'Defender'),
    (48, 'Achraf Hakimi', 'Defender'),
    (49, 'Leandro Paredes', 'Midfielder'),
    (50, 'Marco Verratti', 'Midfielder'),
    (51, 'Georginio Wijnaldum', 'Midfielder'),
    (52, 'Mauro Icardi', 'Forward'),
    (53, 'Kylian Mbappé', 'Forward'),
    (54, 'Neymar Jr.', 'Forward'),
    (55, 'Angel Di María', 'Forward');