INSERT INTO players (id, name, position) VALUES
    (1, 'Lionel Messi', 'Forward'),
    (2, 'Cristiano Ronaldo', 'Forward'),
    (3, 'Kevin De Bruyne', 'Midfielder'),
    (4, 'Virgil van Dijk', 'Defender'),
    (5, 'Sergio Ramos', 'Defender'),
    (6, 'Neymar Jr.', 'Forward'),
    (7, 'Kylian Mbappé', 'Forward'),
    (8, 'Mohamed Salah', 'Forward'),
    (9, 'Robert Lewandowski', 'Forward'),
    (10, 'Eden Hazard', 'Forward'),
    (11, 'Luka Modrić', 'Midfielder'),
    (12, 'Thibaut Courtois', 'Goalkeeper'),
    (13, 'Karim Benzema', 'Forward'),
    (14, 'Toni Kroos', 'Midfielder'),
    (15, 'Fede Valverde', 'Midfielder'),
    (16, 'Ferland Mendy', 'Defender'),
    (17, 'Vinícius Júnior', 'Forward'),
    (18, 'David Alaba', 'Defender'),
    (19, 'Casemiro', 'Midfielder'),
    (20, 'Isco', 'Midfielder'),
    (21, 'Marcelo', 'Defender'),
    (22, 'Eden Hazard', 'Forward'),
    (23, 'Raheem Sterling', 'Forward'),
    (24, 'Phil Foden', 'Midfielder'),
    (25, 'Jack Grealish', 'Forward'),
    (26, 'Riyad Mahrez', 'Forward'),
    (27, 'Bernardo Silva', 'Midfielder'),
    (28, 'Ilkay Gündogan', 'Midfielder'),
    (29, 'Rodri', 'Midfielder'),
    (30, 'Aymeric Laporte', 'Defender'),
    (31, 'John Stones', 'Defender'),
    (32, 'Kyle Walker', 'Defender'),
    (33, 'Ederson', 'Goalkeeper'),
    (34, 'Alisson Becker', 'Goalkeeper'),
    (35, 'Trent Alexander-Arnold', 'Defender'),
    (36, 'Andrew Robertson', 'Defender'),
    (37, 'Mohamed Salah', 'Forward'),
    (38, 'Sadio Mané', 'Forward'),
    (39, 'Thiago Alcântara', 'Midfielder'),
    (40, 'Fabinho', 'Midfielder'),
    (41, 'Jordan Henderson', 'Midfielder'),
    (42, 'Diogo Jota', 'Forward'),
    (43, 'Roberto Firmino', 'Forward'),
    (44, 'Virgil van Dijk', 'Defender'),
    (45, 'Gianluigi Donnarumma', 'Goalkeeper'),
    (46, 'Marquinhos', 'Defender'),
    (47, 'Sergio Ramos', 'Defender'),
    (48, 'Achraf Hakimi', 'Defender'),
    (49, 'Leandro Paredes', 'Midfielder'),
    (50, 'Marco Verratti', 'Midfielder'),
    (51, 'Georginio Wijnaldum', 'Midfielder'),
    (52, 'Mauro Icardi', 'Forward'),
    (53, 'Kylian Mbappé', 'Forward'),
    (54, 'Neymar Jr.', 'Forward'),
    (55, 'Angel Di María', 'Forward'),
    (56, 'Jan Oblak', 'Goalkeeper'),
    (57, 'José Giménez', 'Defender'),
    (58, 'Koke', 'Midfielder'),
    (59, 'Ángel Correa', 'Forward'),
    (60, 'Antoine Griezmann', 'Forward'),
    (61, 'Saúl Ñíguez', 'Midfielder'),
    (62, 'Stefan Savić', 'Defender'),
    (63, 'Rodrigo De Paul', 'Midfielder'),
    (64, 'Mario Hermoso', 'Defender'),
    (65, 'Marcos Llorente', 'Midfielder'),
    (66, 'Memphis Depay', 'Forward'),
    (67, 'Kepa Arrizabalaga', 'Goalkeeper'),
    (68, 'Thiago Silva', 'Defender'),
    (69, 'Reece James', 'Defender'),
    (70, 'Ben Chilwell', 'Defender'),
    (71, 'Enzo Fernández', 'Midfielder'),
    (72, 'Noni Madueke', 'Forward'),
    (73, 'Christopher Nkunku', 'Forward'),
    (74, 'Moisés Caicedo', 'Midfielder'),
    (75, 'Raheem Sterling', 'Forward'),
    (76, 'Malo Gusto', 'Defender'),
    (77, 'Cole Palmer', 'Midfielder'),
    (78, 'Anthony Lopes', 'Goalkeeper'),
    (79, 'Nicolás Tagliafico', 'Defender'),
    (80, 'Corentin Tolisso', 'Midfielder'),
    (81, 'Alexandre Lacazette', 'Forward'),
    (82, 'Rayan Cherki', 'Forward'),
    (83, 'Maxence Caqueret', 'Midfielder'),
    (84, 'Moussa Dembélé', 'Forward'),
    (85, 'Castello Lukeba', 'Defender'),
    (86, 'Tino Kadewere', 'Forward'),
    (87, 'Dejan Lovren', 'Defender'),
    (88, 'Bradley Barcola', 'Midfielder'),
    (89, 'Wojciech Szczęsny', 'Goalkeeper'),
    (90, 'Leonardo Bonucci', 'Defender'),
    (91, 'Federico Chiesa', 'Forward'),
    (92, 'Paul Pogba', 'Midfielder'),
    (93, 'Dusan Vlahovic', 'Forward'),
    (94, 'Adrien Rabiot', 'Midfielder'),
    (95, 'Gleison Bremer', 'Defender'),
    (96, 'Filip Kostić', 'Midfielder'),
    (97, 'Manuel Locatelli', 'Midfielder'),
    (98, 'Danilo', 'Defender'),
    (99, 'Arkadiusz Milik', 'Forward'),
    (100, 'Gregor Kobel', 'Goalkeeper'),
    (101, 'Mats Hummels', 'Defender'),
    (102, 'Niklas Süle', 'Defender'),
    (103, 'Julian Brandt', 'Midfielder'),
    (104, 'Karim Adeyemi', 'Forward'),
    (105, 'Marco Reus', 'Midfielder'),
    (106, 'Sebastian Haller', 'Forward'),
    (107, 'Donyell Malen', 'Forward'),
    (108, 'Emre Can', 'Midfielder'),
    (109, 'Jude Bellingham', 'Midfielder'),
    (110, 'Raphaël Guerreiro', 'Defender');